# Generated by Django 3.1.7 on 2021-03-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20210329_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snnipet',
            field=models.CharField(default='Click link above to read', max_length=255),
        ),
    ]
